version: '3'

services:
  redis:
    image: 'redis:alpine'
    networks:
      - intnet
    volumes:
      - './docker/redis:/data'
  db:
    image: 'postgres'
    networks:
      - intnet
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proposify
  api:
    build: './src/api'
    networks:
      - intnet
    volumes:
      - './docker/api/logs:/root/.npm/_logs/'
    environment:
      REDIS_CONNECTION: redis
      POSTGRES_CONNECTION: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proposify
    ports:
      - 3000:3000
    depends_on:
      - redis
      - db
networks:
  intnet:
